// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCInfomation.proto

package io.grpc;

public final class GRPCInfomation {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_InfoRpcRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_InfoRpcRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_InfoRpcResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_InfoRpcResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\024GRPCInfomation.proto\"L\n\016InfoRpcRequest" +
                        "\022\017\n\007message\030\001 \001(\t\022\024\n\014integerValue\030\002 \001(\005\022" +
                        "\023\n\013doubleValue\030\003 \001(\001\"M\n\017InfoRpcResponse\022" +
                        "\017\n\007message\030\001 \001(\t\022\024\n\014integerValue\030\002 \001(\005\022\023" +
                        "\n\013doubleValue\030\003 \001(\0012L\n\016InfoRpcService\022:\n" +
                        "\023transferInformation\022\017.InfoRpcRequest\032\020." +
                        "InfoRpcResponse\"\000B\t\n\007io.grpcb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_InfoRpcRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_InfoRpcRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_InfoRpcRequest_descriptor,
                new java.lang.String[]{"Message", "IntegerValue", "DoubleValue",});
        internal_static_InfoRpcResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_InfoRpcResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_InfoRpcResponse_descriptor,
                new java.lang.String[]{"Message", "IntegerValue", "DoubleValue",});
    }

    private GRPCInfomation() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface InfoRpcRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:InfoRpcRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string message = 1;</code>
         */
        java.lang.String getMessage();

        /**
         * <code>optional string message = 1;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <code>optional int32 integerValue = 2;</code>
         */
        int getIntegerValue();

        /**
         * <code>optional double doubleValue = 3;</code>
         */
        double getDoubleValue();
    }

    public interface InfoRpcResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:InfoRpcResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string message = 1;</code>
         */
        java.lang.String getMessage();

        /**
         * <code>optional string message = 1;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <code>optional int32 integerValue = 2;</code>
         */
        int getIntegerValue();

        /**
         * <code>optional double doubleValue = 3;</code>
         */
        double getDoubleValue();
    }

    /**
     * <pre>
     * Defining the request body
     * </pre>
     * <p>
     * Protobuf type {@code InfoRpcRequest}
     */
    public static final class InfoRpcRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:InfoRpcRequest)
            InfoRpcRequestOrBuilder {
        public static final int MESSAGE_FIELD_NUMBER = 1;
        public static final int INTEGERVALUE_FIELD_NUMBER = 2;
        public static final int DOUBLEVALUE_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:InfoRpcRequest)
        private static final io.grpc.GRPCInfomation.InfoRpcRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<InfoRpcRequest>
                PARSER = new com.google.protobuf.AbstractParser<InfoRpcRequest>() {
            public InfoRpcRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new InfoRpcRequest(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new io.grpc.GRPCInfomation.InfoRpcRequest();
        }

        private volatile java.lang.Object message_;
        private int integerValue_;
        private double doubleValue_;
        private byte memoizedIsInitialized = -1;
        // Use InfoRpcRequest.newBuilder() to construct.
        private InfoRpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private InfoRpcRequest() {
            message_ = "";
            integerValue_ = 0;
            doubleValue_ = 0D;
        }

        private InfoRpcRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                        case 16: {

                            integerValue_ = input.readInt32();
                            break;
                        }
                        case 25: {

                            doubleValue_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.grpc.GRPCInfomation.internal_static_InfoRpcRequest_descriptor;
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.grpc.GRPCInfomation.InfoRpcRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static io.grpc.GRPCInfomation.InfoRpcRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<InfoRpcRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.grpc.GRPCInfomation.internal_static_InfoRpcRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.grpc.GRPCInfomation.InfoRpcRequest.class, io.grpc.GRPCInfomation.InfoRpcRequest.Builder.class);
        }

        /**
         * <code>optional string message = 1;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>optional string message = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int32 integerValue = 2;</code>
         */
        public int getIntegerValue() {
            return integerValue_;
        }

        /**
         * <code>optional double doubleValue = 3;</code>
         */
        public double getDoubleValue() {
            return doubleValue_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getMessageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
            }
            if (integerValue_ != 0) {
                output.writeInt32(2, integerValue_);
            }
            if (doubleValue_ != 0D) {
                output.writeDouble(3, doubleValue_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMessageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
            }
            if (integerValue_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, integerValue_);
            }
            if (doubleValue_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, doubleValue_);
            }
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.grpc.GRPCInfomation.InfoRpcRequest)) {
                return super.equals(obj);
            }
            io.grpc.GRPCInfomation.InfoRpcRequest other = (io.grpc.GRPCInfomation.InfoRpcRequest) obj;

            boolean result = true;
            result = result && getMessage()
                    .equals(other.getMessage());
            result = result && (getIntegerValue()
                    == other.getIntegerValue());
            result = result && (
                    java.lang.Double.doubleToLongBits(getDoubleValue())
                            == java.lang.Double.doubleToLongBits(
                            other.getDoubleValue()));
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (37 * hash) + INTEGERVALUE_FIELD_NUMBER;
            hash = (53 * hash) + getIntegerValue();
            hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getDoubleValue()));
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<InfoRpcRequest> getParserForType() {
            return PARSER;
        }

        public io.grpc.GRPCInfomation.InfoRpcRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * <pre>
         * Defining the request body
         * </pre>
         * <p>
         * Protobuf type {@code InfoRpcRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:InfoRpcRequest)
                io.grpc.GRPCInfomation.InfoRpcRequestOrBuilder {
            private java.lang.Object message_ = "";
            private int integerValue_;
            private double doubleValue_;

            // Construct using io.grpc.GRPCInfomation.InfoRpcRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.grpc.GRPCInfomation.internal_static_InfoRpcRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.grpc.GRPCInfomation.internal_static_InfoRpcRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.grpc.GRPCInfomation.InfoRpcRequest.class, io.grpc.GRPCInfomation.InfoRpcRequest.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                message_ = "";

                integerValue_ = 0;

                doubleValue_ = 0D;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.grpc.GRPCInfomation.internal_static_InfoRpcRequest_descriptor;
            }

            public io.grpc.GRPCInfomation.InfoRpcRequest getDefaultInstanceForType() {
                return io.grpc.GRPCInfomation.InfoRpcRequest.getDefaultInstance();
            }

            public io.grpc.GRPCInfomation.InfoRpcRequest build() {
                io.grpc.GRPCInfomation.InfoRpcRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.grpc.GRPCInfomation.InfoRpcRequest buildPartial() {
                io.grpc.GRPCInfomation.InfoRpcRequest result = new io.grpc.GRPCInfomation.InfoRpcRequest(this);
                result.message_ = message_;
                result.integerValue_ = integerValue_;
                result.doubleValue_ = doubleValue_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.grpc.GRPCInfomation.InfoRpcRequest) {
                    return mergeFrom((io.grpc.GRPCInfomation.InfoRpcRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.grpc.GRPCInfomation.InfoRpcRequest other) {
                if (other == io.grpc.GRPCInfomation.InfoRpcRequest.getDefaultInstance()) return this;
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                if (other.getIntegerValue() != 0) {
                    setIntegerValue(other.getIntegerValue());
                }
                if (other.getDoubleValue() != 0D) {
                    setDoubleValue(other.getDoubleValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.grpc.GRPCInfomation.InfoRpcRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.grpc.GRPCInfomation.InfoRpcRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 integerValue = 2;</code>
             */
            public int getIntegerValue() {
                return integerValue_;
            }

            /**
             * <code>optional int32 integerValue = 2;</code>
             */
            public Builder setIntegerValue(int value) {

                integerValue_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 integerValue = 2;</code>
             */
            public Builder clearIntegerValue() {

                integerValue_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional double doubleValue = 3;</code>
             */
            public double getDoubleValue() {
                return doubleValue_;
            }

            /**
             * <code>optional double doubleValue = 3;</code>
             */
            public Builder setDoubleValue(double value) {

                doubleValue_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional double doubleValue = 3;</code>
             */
            public Builder clearDoubleValue() {

                doubleValue_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:InfoRpcRequest)
        }

    }

    /**
     * <pre>
     * Defining the response content
     * </pre>
     * <p>
     * Protobuf type {@code InfoRpcResponse}
     */
    public static final class InfoRpcResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:InfoRpcResponse)
            InfoRpcResponseOrBuilder {
        public static final int MESSAGE_FIELD_NUMBER = 1;
        public static final int INTEGERVALUE_FIELD_NUMBER = 2;
        public static final int DOUBLEVALUE_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:InfoRpcResponse)
        private static final io.grpc.GRPCInfomation.InfoRpcResponse DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<InfoRpcResponse>
                PARSER = new com.google.protobuf.AbstractParser<InfoRpcResponse>() {
            public InfoRpcResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new InfoRpcResponse(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new io.grpc.GRPCInfomation.InfoRpcResponse();
        }

        private volatile java.lang.Object message_;
        private int integerValue_;
        private double doubleValue_;
        private byte memoizedIsInitialized = -1;
        // Use InfoRpcResponse.newBuilder() to construct.
        private InfoRpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private InfoRpcResponse() {
            message_ = "";
            integerValue_ = 0;
            doubleValue_ = 0D;
        }

        private InfoRpcResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                        case 16: {

                            integerValue_ = input.readInt32();
                            break;
                        }
                        case 25: {

                            doubleValue_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.grpc.GRPCInfomation.internal_static_InfoRpcResponse_descriptor;
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.grpc.GRPCInfomation.InfoRpcResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static io.grpc.GRPCInfomation.InfoRpcResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<InfoRpcResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.grpc.GRPCInfomation.internal_static_InfoRpcResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.grpc.GRPCInfomation.InfoRpcResponse.class, io.grpc.GRPCInfomation.InfoRpcResponse.Builder.class);
        }

        /**
         * <code>optional string message = 1;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>optional string message = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int32 integerValue = 2;</code>
         */
        public int getIntegerValue() {
            return integerValue_;
        }

        /**
         * <code>optional double doubleValue = 3;</code>
         */
        public double getDoubleValue() {
            return doubleValue_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getMessageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
            }
            if (integerValue_ != 0) {
                output.writeInt32(2, integerValue_);
            }
            if (doubleValue_ != 0D) {
                output.writeDouble(3, doubleValue_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMessageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
            }
            if (integerValue_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, integerValue_);
            }
            if (doubleValue_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, doubleValue_);
            }
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.grpc.GRPCInfomation.InfoRpcResponse)) {
                return super.equals(obj);
            }
            io.grpc.GRPCInfomation.InfoRpcResponse other = (io.grpc.GRPCInfomation.InfoRpcResponse) obj;

            boolean result = true;
            result = result && getMessage()
                    .equals(other.getMessage());
            result = result && (getIntegerValue()
                    == other.getIntegerValue());
            result = result && (
                    java.lang.Double.doubleToLongBits(getDoubleValue())
                            == java.lang.Double.doubleToLongBits(
                            other.getDoubleValue()));
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (37 * hash) + INTEGERVALUE_FIELD_NUMBER;
            hash = (53 * hash) + getIntegerValue();
            hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getDoubleValue()));
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<InfoRpcResponse> getParserForType() {
            return PARSER;
        }

        public io.grpc.GRPCInfomation.InfoRpcResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * <pre>
         * Defining the response content
         * </pre>
         * <p>
         * Protobuf type {@code InfoRpcResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:InfoRpcResponse)
                io.grpc.GRPCInfomation.InfoRpcResponseOrBuilder {
            private java.lang.Object message_ = "";
            private int integerValue_;
            private double doubleValue_;

            // Construct using io.grpc.GRPCInfomation.InfoRpcResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.grpc.GRPCInfomation.internal_static_InfoRpcResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.grpc.GRPCInfomation.internal_static_InfoRpcResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.grpc.GRPCInfomation.InfoRpcResponse.class, io.grpc.GRPCInfomation.InfoRpcResponse.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                message_ = "";

                integerValue_ = 0;

                doubleValue_ = 0D;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.grpc.GRPCInfomation.internal_static_InfoRpcResponse_descriptor;
            }

            public io.grpc.GRPCInfomation.InfoRpcResponse getDefaultInstanceForType() {
                return io.grpc.GRPCInfomation.InfoRpcResponse.getDefaultInstance();
            }

            public io.grpc.GRPCInfomation.InfoRpcResponse build() {
                io.grpc.GRPCInfomation.InfoRpcResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.grpc.GRPCInfomation.InfoRpcResponse buildPartial() {
                io.grpc.GRPCInfomation.InfoRpcResponse result = new io.grpc.GRPCInfomation.InfoRpcResponse(this);
                result.message_ = message_;
                result.integerValue_ = integerValue_;
                result.doubleValue_ = doubleValue_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.grpc.GRPCInfomation.InfoRpcResponse) {
                    return mergeFrom((io.grpc.GRPCInfomation.InfoRpcResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.grpc.GRPCInfomation.InfoRpcResponse other) {
                if (other == io.grpc.GRPCInfomation.InfoRpcResponse.getDefaultInstance()) return this;
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                if (other.getIntegerValue() != 0) {
                    setIntegerValue(other.getIntegerValue());
                }
                if (other.getDoubleValue() != 0D) {
                    setDoubleValue(other.getDoubleValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.grpc.GRPCInfomation.InfoRpcResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.grpc.GRPCInfomation.InfoRpcResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 integerValue = 2;</code>
             */
            public int getIntegerValue() {
                return integerValue_;
            }

            /**
             * <code>optional int32 integerValue = 2;</code>
             */
            public Builder setIntegerValue(int value) {

                integerValue_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 integerValue = 2;</code>
             */
            public Builder clearIntegerValue() {

                integerValue_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional double doubleValue = 3;</code>
             */
            public double getDoubleValue() {
                return doubleValue_;
            }

            /**
             * <code>optional double doubleValue = 3;</code>
             */
            public Builder setDoubleValue(double value) {

                doubleValue_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional double doubleValue = 3;</code>
             */
            public Builder clearDoubleValue() {

                doubleValue_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:InfoRpcResponse)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
